# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qrn < Formula
  desc "qrn is a database load testing tool."
  homepage "https://github.com/winebarrel/qrn"
  version "2.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/qrn/releases/download/v2.1.0/qrn_2.1.0_darwin_arm64.tar.gz"
      sha256 "13c690108933af30b4b570d3584d48d8e690bc3a756047fcc2eb8b432f70f3e8"

      def install
        bin.install 'qrn'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/qrn/releases/download/v2.1.0/qrn_2.1.0_darwin_amd64.tar.gz"
      sha256 "ba5b92bbe268bcba1900a51e2b5307008604ebcd805892f5504c0b0fb1d72b34"

      def install
        bin.install 'qrn'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/qrn/releases/download/v2.1.0/qrn_2.1.0_linux_amd64.tar.gz"
      sha256 "f499a2796747a95b277f06ec7d63b9c776f30cddccfd39031b8cbfa4324dc37e"

      def install
        bin.install 'qrn'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/qrn/releases/download/v2.1.0/qrn_2.1.0_linux_arm64.tar.gz"
      sha256 "90b9637be24ae39b9031e9c0625a89e5d6e2bd4ca5ba6ecc0dcf12758008913e"

      def install
        bin.install 'qrn'
      end
    end
  end
end
