# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qrn < Formula
  desc "qrn is a database load testing tool."
  homepage "https://github.com/winebarrel/qrn"
  version "2.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/qrn/releases/download/v2.0.2/qrn_2.0.2_darwin_arm64.tar.gz"
      sha256 "f9866209a8866868247827df35bd7071f90ffb1df33ce28779ca4daeb861d0c3"

      def install
        bin.install 'qrn'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/qrn/releases/download/v2.0.2/qrn_2.0.2_darwin_amd64.tar.gz"
      sha256 "6919b66ef76336b916cf715f9121941f6a9844a27878a44c8dccf74988ab5d08"

      def install
        bin.install 'qrn'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/qrn/releases/download/v2.0.2/qrn_2.0.2_linux_amd64.tar.gz"
      sha256 "97c150fef48cebac0fac92361e0e8a302a431f67ee4aa706b60a6ba12523801a"

      def install
        bin.install 'qrn'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/qrn/releases/download/v2.0.2/qrn_2.0.2_linux_arm64.tar.gz"
      sha256 "4238d88fdecb21251a1a6987a11eb67a4c1073cac97d296fe026fb16629b0c97"

      def install
        bin.install 'qrn'
      end
    end
  end
end
