# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qrn < Formula
  desc "qrn is a database load testing tool."
  homepage "https://github.com/winebarrel/qrn"
  version "2.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/qrn/releases/download/v2.0.0/qrn_2.0.0_darwin_amd64.tar.gz"
      sha256 "256bff99f784a4d6f5affb5770a608110feb02b90e174ce0f693ac2265bb67be"

      def install
        bin.install 'qrn'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/qrn/releases/download/v2.0.0/qrn_2.0.0_darwin_arm64.tar.gz"
      sha256 "96be22ad9f30bbab01923f2afdbffad46f3047db5a6ef2ecb04fa7720e0859aa"

      def install
        bin.install 'qrn'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/qrn/releases/download/v2.0.0/qrn_2.0.0_linux_amd64.tar.gz"
      sha256 "3a93d5fca1aac42ddf362b26b3e1b236b1b45ce95a8eebd35d1bad935d7098fe"

      def install
        bin.install 'qrn'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/qrn/releases/download/v2.0.0/qrn_2.0.0_linux_arm64.tar.gz"
      sha256 "67a7cf29a9e150f23e7b4099e7864647ff6382271527b80ac20923e6bd008116"

      def install
        bin.install 'qrn'
      end
    end
  end
end
